package org.epiphany.Enums.Systems.Generation;

public enum EGenerationNames {

    /*First Names*/

    /*Masc*/

    AARON("First", "Masc", "Aaron"),
    ADAM("First","Masc", "Adam"),
    ALEXANDER("First","Masc", "Alexander"),
    DRUST("First","Masc", "Drust"),
    ETHAN("First","Masc", "Ethan"),
    JAMES("First","Masc", "James"),
    JOHN("First","Masc", "John"),
    DANZYG("First","Masc", "Danzyg"),
    DRUSYC("First","Masc", "Drusyć"),
    KACPER("First","Masc", "Kacper"),
    KAMIL("First","Masc", "Kamil"),
    KRZYSZTOF("First","Masc", "Krzysztof"),
    LUKASZ("First","Masc", "Łukasz"),
    MATEUSZ("First","Masc", "Mateusz"),
    MICHAEL("First","Masc", "Michael"),
    MICHAŁ("First","Masc", "Michał"),
    NATHAN("First","Masc", "Nathan"),
    NOAH("First","Masc", "Noah"),
    OLIVER("First","Masc", "Oliver"),
    TIDUS("First","Masc", "Tidus"),
    AURON("First","Masc", "Auron"),
    ORON("First","Masc", "Oron"),
    XION("First","Masc", "Xion"),
    ZACK("First","Masc", "Zack"),
    ZIDANE("First","Masc", "Zidane"),

    /*Ambi*/

    ALEX("First","Ambi", "Alex"),
    CASS("First","Ambi", "Cass"),
    KIM("First","Ambi", "Kim"),
    LEX("First","Ambi", "Lex"),
    RYDER("First","Ambi", "Ryder"),
    TAYLOR("First","Ambi", "Taylor"),
    JORDAN("First","Ambi", "Jordan"),
    CASEY("First","Ambi", "Casey"),
    RILEY("First","Ambi", "Riley"),
    SKYLER("First","Ambi", "Skyler"),
    FINLEY("First","Ambi", "Finley"),
    QUINN("First","Ambi", "Quinn"),
    AVERY("First","Ambi", "Avery"),
    REESE("First","Ambi", "Reese"),
    PAYTON("First","Ambi", "Payton"),
    ELLIS("First","Ambi", "Ellis"),
    HUNTER("First","Ambi", "Hunter"),
    ROWAN("First","Ambi", "Rowan"),
    SAGE("First","Ambi", "Sage"),
    TATUM("First","Ambi", "Tatum"),
    KRYS("First","Ambi", "Krys"),
    REN("First","Ambi", "Ren"),
    SORREN("First","Ambi", "Sorren"),
    LOREN("First","Ambi", "Loren"),
    RIN("First","Ambi", "Rin"),

    /*Fem*/

    AMELIA("First","Fem", "Amelia"),
    AURORA("First","Fem", "Aurora"),
    AVA("First","Fem", "Ava"),
    CHARLOTTE("First","Fem", "Charlotte"),
    EMMA("First","Fem", "Emma"),
    ISABELLA("First","Fem", "Isabella"),
    OLIVIA("First","Fem", "Olivia"),
    SOPHIA("First","Fem", "Sophia"),
    ZOE("First","Fem", "Zoe"),
    DRUSILLA("First","Fem", "Drusilla"),
    DRUSYLA("First","Fem", "Drusyła"),
    KATARZYNA("First","Fem", "Katarzyna"),
    MARIA("First","Fem", "Maria"),
    NATALIA("First","Fem", "Natalia"),
    NIKOLA("First","Fem", "Nikola"),
    RACHEL("First","Fem", "Rachel"),
    SERENA("First","Fem", "Serena"),
    TATYANA("First","Fem", "Tatyana"),
    YVONNE("First","Fem", "Yvonne"),
    YVETTE("First","Fem", "Yvette"),
    YVETTA("First","Fem", "Yvetta"),
    RENA("First","Fem", "Rena"),
    LENA("First","Fem", "Lena"),
    LUNA("First","Fem", "Luna"),
    ARIA("First","Fem", "Aria"),
    LYRA("First","Fem", "Lyra"),
    MIA("First","Fem", "Mia"),
    LILIA("First","Fem", "Lilia"),
    LILYA("First","Fem", "Lilya"),
    TIFFANY("First","Fem", "Tiffany"),
    BRENDA("First","Fem", "Brenda"),

    /*Last Names*/

    /*All ambi*/

    STORM("Last","Ambi", "Storm"),
    SHADOW("Last","Ambi", "Shadow"),
    RAIN("Last","Ambi", "Rain"),
    NIGHT("Last","Ambi", "Night"),
    DAWN("Last","Ambi", "Dawn"),
    SKY("Last","Ambi", "Sky"),
    MOON("Last","Ambi", "Moon"),
    STAR("Last","Ambi", "Star"),
    FROST("Last","Ambi", "Frost"),
    FLAME("Last","Ambi", "Flame"),
    WOLF("Last","Ambi", "Wolf"),
    FOX("Last","Ambi", "Fox"),
    HAWK("Last","Ambi", "Hawk"),
    LION("Last","Ambi", "Lion"),
    BEAR("Last","Ambi", "Bear"),
    DRAGON("Last","Ambi", "Dragon"),
    TIGER("Last","Ambi", "Tiger"),
    PHOENIX("Last","Ambi", "Phoenix"),
    COBRA("Last","Ambi", "Cobra"),
    VIPER("Last","Ambi", "Viper"),
    EAGLE("Last","Ambi", "Eagle"),
    RANGER("Last","Ambi", "Ranger"),
    WARDEN("Last","Ambi", "Warden"),
    BLADE("Last","Ambi", "Blade"),
    SHIELD("Last","Ambi", "Shield"),
    ARROW("Last","Ambi", "Arrow"),
    BOW("Last","Ambi", "Bow"),
    SPEAR("Last","Ambi", "Spear"),
    AXE("Last","Ambi", "Axe"),
    HAMMER("Last","Ambi", "Hammer"),
    SWORD("Last","Ambi", "Sword"),
    DANE("Last","Ambi", "Dane"),
    STARK("Last","Ambi", "Stark"),
    VALE("Last","Ambi", "Vale"),
    REED("Last","Ambi", "Reed"),
    SNOW("Last","Ambi", "Snow"),
    DANSI("Last","Ambi", "Dansi"),
    DANSY("Last","Ambi", "Dansy"),
    KOWALSKI("Last","Ambi", "Kowalski"),
    NOWAK("Last","Ambi", "Nowak"),
    HERMES("Last","Ambi", "Hermes"),
    ATHENA("Last","Ambi", "Athena"),
    ZEUS("Last","Ambi", "Zeus"),
    HERM("Last","Ambi", "Herm"),
    ATHEN("Last","Ambi", "Athen"),
    ZEU("Last","Ambi", "Zeu"),
    TITAN("Last","Ambi", "Titan"),
    CAESAR("Last","Ambi", "Caesar"),
    AUGUSTUS("Last","Ambi", "Augustus"),
    BRUTUS("Last","Ambi", "Brutus"),
    BUI("Last","Ambi", "Bui"),
    NGUYEN("Last","Ambi", "Nguyen"),
    TRAN("Last","Ambi", "Tran"),
    LE("Last","Ambi", "Le"),
    PHAM("Last","Ambi", "Pham"),
    HOANG("Last","Ambi", "Hoang"),
    HUYNH("Last","Ambi", "Huynh"),
    PHUONG("Last","Ambi", "Phoung"),
    DANG("Last","Ambi", "Dang"),
    DO("Last","Ambi", "Do"),
    LUCIEN("Last","Ambi", "Lucien"),
    MARCEL("Last","Ambi", "Marcel"),
    RENARD("Last","Ambi", "Renard"),
    BEAUX("Last","Ambi", "Beaux"),
    LEMAIRE("Last","Ambi", "Lemaire"),
    MOREAU("Last","Ambi", "Moreau"),
    DUBOIS("Last","Ambi", "Dubois"),
    LEBLANC("Last","Ambi", "Leblanc"),
    FAURE("Last","Ambi", "Faure"),
    RENAUD("Last","Ambi", "Renaud"),
    GIRARD("Last","Ambi", "Girard"),
    BONN("Last","Ambi", "Bonn"),
    LYNCH("Last","Ambi", "Lynch"),
    OCONNOR("Last","Ambi", "O'Connor"),
    MURPHY("Last","Ambi", "Murphy"),
    KELLY("Last","Ambi", "Kelly"),
    SULLIVAN("Last","Ambi", "Sullivan"),
    REILLY("Last","Ambi", "Reilly"),
    WALSH("Last","Ambi", "Walsh"),
    RYAN("Last","Ambi", "Ryan"),
    GALLAGHER("Last","Ambi", "Gallagher"),
    DOHERTY("Last","Ambi", "Doherty"),
    MCGEE("Last","Ambi", "McGee"),
    MCKENNA("Last","Ambi", "McKenna"),
    OSHEA("Last","Ambi", "O\'Shea"),
    ONEILL("Last","Ambi", "O\'Neill"),
    FLORES("Last","Ambi", "Flores"),
    RIVERA("Last","Ambi", "Rivera"),
    GARCIA("Last","Ambi", "Garcia"),
    MARTINEZ("Last","Ambi", "Martinez"),
    RODRIGUEZ("Last","Ambi", "Rodriguez"),
    HERNANDEZ("Last","Ambi", "Hernandez"),
    LOPEZ("Last","Ambi", "Lopez"),
    GONZALEZ("Last","Ambi", "Gonzalez"),
    PEREZ("Last","Ambi", "Perez"),
    SANCHEZ("Last","Ambi", "Sanchez"),
    RAMIREZ("Last","Ambi", "Ramirez"),
    TORRES("Last","Ambi", "Torres"),
    RUIZ("Last","Ambi", "Ruiz"),
    CHISMORE("Last","Ambi", "Chismore"),
    CHISMOR("Last","Ambi", "Chismor"),
    CHISMARE("Last","Ambi", "Chismare"),
    DANSZ("Last","Ambi", "Dansz"),
    DANSZC("Last","Ambi", "Danszc"),
    DANSZYC("Last","Ambi", "Danszyc"),
    DANSZYK("Last","Ambi", "Danszyk"),
    DANSKY("Last","Ambi", "Dansky"),
    DANSKI("Last","Ambi", "Danski"),
    DANSKYI("Last","Ambi", "Danskyi"),
    DANSZIK("Last","Ambi", "Danszik"),
    ZAYN("Last","Ambi", "Zayn"),
    MALIK("Last","Ambi", "Malik"),
    HODGDON("Last","Ambi", "Hodgdon"),
    MERRICK("Last","Ambi", "Merrick"),
    QUINNELL("Last","Ambi", "Quinnell"),
    QUINNEL("Last","Ambi", "Quinnel"),
    QUINNLE("Last","Ambi", "Quinnle"),
    OAKEN("Last","Ambi", "Oaken"),
    OAKENFOLD("Last","Ambi", "Oakenfold"),
    OAKENFOLDS("Last","Ambi", "Oakenfolds"),
    OAKENFOLDE("Last","Ambi", "Oakenfolde"),
    OAKENFIELD("Last","Ambi", "Oakenfield"),
    OAKENFIELDS("Last","Ambi", "Oakenfields"),
    RANS("Last","Ambi", "Rans"),
    HEI("Last","Ambi", "Hei"),
    KAI("Last","Ambi", "Kai"),
    HAI("Last","Ambi", "Hai"),
    HUI("Last","Ambi", "Hui"),
    MAI("Last","Ambi", "Mai");

    private final String nameSpace;
    private final String presentingGender;
    private final String name;

    EGenerationNames(String nameSpace, String presentingGender, String name) {
        this.nameSpace = nameSpace;
        this.presentingGender = presentingGender;
        this.name = name;
    }
}
